name: Test

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: librarian
          POSTGRES_PASSWORD: password
          POSTGRES_USER: librarian
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        sudo apt-get install -y libnfs-dev imagemagick ghostscript-x

        python -m pip install --upgrade pip
        python -m pip install poetry

        poetry install

        # Needed to fix imagemagick, see Dockerfile or
        # https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion
        sudo cp policy.xml /etc/ImageMagick-6/policy.xml

    - name: Run Tests
      run: |
        make test-coverage
      env:
        DATABASE_URL: postgres://librarian:password@localhost/librarian

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
